// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllDevicesList() {
  return window['go']['main']['App']['GetAllDevicesList']();
}

export function GetOverviewInfo() {
  return window['go']['main']['App']['GetOverviewInfo']();
}
